import { useState } from 'react';
import { Bot, Sparkles, AlertCircle, Key, BarChart2, TrendingUp } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { fetchFearGreed, fetchBatchQuotes, fetchSectors } from '../services/api';
import {
  runAIPrompt, getActiveProvider, PROVIDER_LABELS,
  buildMarketPrompt, buildSymbolPrompt,
} from '../services/aiService';
import { useWatchlistStore } from '../store/watchlistStore';
import { useQuote } from '../hooks/useQuotes';
import { useAnalystRatings } from '../hooks/useAnalystRatings';
import { useEarnings } from '../hooks/useEarnings';
import { useInstitutional } from '../hooks/useInstitutional';
import type { FearGreedData, Quote, SectorData } from '../types';
import clsx from 'clsx';

const MOVERS_UNIVERSE = [
  'AAPL','MSFT','NVDA','GOOGL','META','AMZN','TSLA','AMD','AVGO','JPM',
  'GS','V','MA','UNH','LLY','XOM','CVX','SPY','QQQ','IWM',
];

type Tab = 'market' | 'symbol';

function NoKeyNote() {
  return (
    <div className="bg-bg-card border border-yellow-900/40 rounded-lg p-4 flex gap-3">
      <Key className="w-4 h-4 text-yellow-400 shrink-0 mt-0.5" />
      <div className="space-y-1">
        <p className="text-xs font-medium text-yellow-400">No AI Provider Configured</p>
        <p className="text-xs text-text-muted leading-relaxed">
          Add a free <strong className="text-gray-300">Gemini</strong> or <strong className="text-gray-300">Groq</strong> key in{' '}
          <strong className="text-gray-300">Settings</strong> (top-right gear icon) to enable AI analysis.
          Both are completely free — Gemini at aistudio.google.com, Groq at console.groq.com.
        </p>
      </div>
    </div>
  );
}

function ProviderBadge() {
  const provider = getActiveProvider();
  if (!provider) return null;
  const colors: Record<string, string> = {
    gemini: 'text-blue-400 bg-blue-400/10',
    groq: 'text-orange-400 bg-orange-400/10',
    claude: 'text-purple-400 bg-purple-400/10',
  };
  return (
    <span className={clsx('text-[10px] px-2 py-0.5 rounded font-medium', colors[provider])}>
      {PROVIDER_LABELS[provider]}
    </span>
  );
}

function AnalysisCard({ text, provider, symbol }: { text: string; provider: string | null; symbol?: string }) {
  return (
    <div className="bg-bg-card border border-border-dim rounded-lg p-5 space-y-3">
      <div className="flex items-center gap-2 mb-2">
        <Bot className="w-4 h-4 text-accent" />
        <span className="text-xs font-semibold text-white">
          {symbol ? `${symbol} Analysis` : 'Market Analysis'}
        </span>
        <span className="text-xs text-text-muted ml-auto">
          {new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
        </span>
      </div>
      <div className="text-xs text-gray-300 leading-relaxed whitespace-pre-wrap">{text}</div>
      <p className="text-[10px] text-text-muted/60 pt-1 border-t border-border-dim">
        Generated by {provider ? PROVIDER_LABELS[provider as keyof typeof PROVIDER_LABELS] : 'AI'} · For informational purposes only. Not financial advice.
      </p>
    </div>
  );
}

// ─── Market Tab ───────────────────────────────────────────────────────────────

function MarketTab() {
  const [analysis, setAnalysis] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const provider = getActiveProvider();

  const { data: fgData } = useQuery<FearGreedData>({ queryKey: ['fear-greed'], queryFn: fetchFearGreed, staleTime: 300_000 });
  const { data: quotes = [] } = useQuery<Quote[]>({ queryKey: ['quotes', MOVERS_UNIVERSE.join(',')], queryFn: () => fetchBatchQuotes(MOVERS_UNIVERSE), staleTime: 60_000 });
  const { data: sectors = [] } = useQuery<SectorData[]>({ queryKey: ['sectors'], queryFn: fetchSectors, staleTime: 300_000 });

  async function analyse() {
    setLoading(true); setError(''); setAnalysis('');
    try {
      const sorted = [...quotes].sort((a, b) => b.changePercent - a.changePercent);
      const prompt = buildMarketPrompt({
        fearGreed: fgData?.fgi?.now ?? { value: 50, valueText: 'Neutral' },
        vix: quotes.find((q) => q.symbol === '^VIX')?.price ?? null,
        topGainers: sorted.slice(0, 5).map((q) => ({ symbol: q.symbol, changePercent: q.changePercent })),
        topLosers: sorted.slice(-5).reverse().map((q) => ({ symbol: q.symbol, changePercent: q.changePercent })),
        sectors: sectors.map((s) => ({ name: s.name, changePercent: s.changePercent })),
      });
      setAnalysis(await runAIPrompt(prompt));
    } catch (e: unknown) { setError((e as Error).message ?? 'Analysis failed'); }
    finally { setLoading(false); }
  }

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="bg-bg-card border border-border-dim rounded-lg p-3">
          <p className="text-xs text-text-muted mb-0.5">Fear & Greed</p>
          <p className="text-sm font-bold text-white">{fgData?.fgi?.now?.value ?? '—'}</p>
          <p className="text-xs text-text-muted">{fgData?.fgi?.now?.valueText ?? '—'}</p>
        </div>
        <div className="bg-bg-card border border-border-dim rounded-lg p-3">
          <p className="text-xs text-text-muted mb-0.5">VIX</p>
          <p className="text-sm font-bold text-white">{quotes.find((q) => q.symbol === '^VIX')?.price?.toFixed(2) ?? '—'}</p>
          <p className="text-xs text-text-muted">Volatility Index</p>
        </div>
        <div className="bg-bg-card border border-border-dim rounded-lg p-3">
          <p className="text-xs text-text-muted mb-0.5">Symbols</p>
          <p className="text-sm font-bold text-white">{MOVERS_UNIVERSE.length}</p>
          <p className="text-xs text-text-muted">Tracked</p>
        </div>
        <div className="bg-bg-card border border-border-dim rounded-lg p-3">
          <p className="text-xs text-text-muted mb-0.5">Sectors</p>
          <p className="text-sm font-bold text-white">{sectors.length}</p>
          <p className="text-xs text-text-muted">Monitored</p>
        </div>
      </div>

      <button
        onClick={analyse}
        disabled={loading || !provider}
        className="flex items-center justify-center gap-2 w-full sm:w-auto sm:px-6 bg-accent hover:bg-accent-hover disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg py-2.5 text-sm font-medium transition-colors"
      >
        {loading ? <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />Analysing…</> : <><Sparkles className="w-4 h-4" />Analyse Market</>}
      </button>

      {error && <div className="bg-bg-card border border-red-900/40 rounded-lg p-4 flex gap-2"><AlertCircle className="w-4 h-4 text-red-400 shrink-0 mt-0.5" /><p className="text-xs text-red-400">{error}</p></div>}
      {analysis && <AnalysisCard text={analysis} provider={provider} />}
      {!analysis && !error && !loading && (
        <div className="bg-bg-card border border-border-dim rounded-lg p-8 text-center space-y-2">
          <Bot className="w-8 h-8 text-text-muted/40 mx-auto" />
          <p className="text-sm text-text-muted">Click "Analyse Market" for an AI market summary</p>
          <p className="text-xs text-text-muted/60">Uses live Fear & Greed, VIX, movers, and sector data</p>
        </div>
      )}
    </div>
  );
}

// ─── Symbol Tab ───────────────────────────────────────────────────────────────

function SymbolTab() {
  const [analysis, setAnalysis] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [inputSymbol, setInputSymbol] = useState('');
  const provider = getActiveProvider();

  const selectedSymbol = useWatchlistStore((s) => s.selectedSymbol);
  const activeSymbol = (inputSymbol || selectedSymbol || 'AAPL').toUpperCase();

  const { data: quote } = useQuote(activeSymbol);
  const { data: ratings } = useAnalystRatings(activeSymbol);
  const { data: earnings } = useEarnings(activeSymbol);
  const { data: institutional } = useInstitutional(activeSymbol);

  const today = new Date().toISOString().slice(0, 10);
  const nextEarnings = earnings?.find((e) => e.date >= today);
  const lastEarnings = earnings?.filter((e) => e.date < today).at(-1);

  const latest = ratings?.[0];
  const totalRatings = latest ? latest.strongBuy + latest.buy + latest.hold + latest.sell + latest.strongSell : 0;
  const consensus = (() => {
    if (!latest || totalRatings === 0) return null;
    const score = (latest.strongBuy * 5 + latest.buy * 4 + latest.hold * 3 + latest.sell * 2 + latest.strongSell * 1) / totalRatings;
    if (score >= 4.5) return 'Strong Buy';
    if (score >= 3.5) return 'Buy';
    if (score >= 2.5) return 'Hold';
    if (score >= 1.5) return 'Sell';
    return 'Strong Sell';
  })();

  async function analyse() {
    if (!quote) return;
    setLoading(true); setError(''); setAnalysis('');
    try {
      const prompt = buildSymbolPrompt({
        symbol: activeSymbol,
        price: quote.price,
        changePercent: quote.changePercent,
        change: quote.change,
        open: quote.open,
        high: quote.high,
        low: quote.low,
        previousClose: quote.previousClose,
        volume: quote.volume,
        marketCap: quote.marketCap,
        pe: quote.pe,
        analystConsensus: consensus ?? undefined,
        analystCount: totalRatings || undefined,
        nextEarnings: nextEarnings?.date,
        lastEarningsSurprise: lastEarnings?.surprise ?? undefined,
        institutionPct: institutional?.institutionPct,
        insiderPct: institutional?.insiderPct,
      });
      setAnalysis(await runAIPrompt(prompt));
    } catch (e: unknown) { setError((e as Error).message ?? 'Analysis failed'); }
    finally { setLoading(false); }
  }

  return (
    <div className="space-y-4">
      {/* Symbol input */}
      <div className="flex gap-2">
        <input
          type="text"
          value={inputSymbol}
          onChange={(e) => setInputSymbol(e.target.value.toUpperCase())}
          placeholder={activeSymbol}
          className="flex-1 bg-bg-hover border border-border-dim rounded px-3 py-2 text-sm text-white placeholder-text-muted focus:outline-none focus:border-accent font-mono uppercase"
        />
        <button
          onClick={analyse}
          disabled={loading || !provider || !quote}
          className="flex items-center gap-2 px-4 bg-accent hover:bg-accent-hover disabled:opacity-50 disabled:cursor-not-allowed text-white rounded py-2 text-sm font-medium transition-colors"
        >
          {loading ? <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <Sparkles className="w-4 h-4" />}
          Analyse
        </button>
      </div>

      {/* Symbol snapshot */}
      {quote && (
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          <div className="bg-bg-card border border-border-dim rounded-lg p-3">
            <p className="text-xs text-text-muted mb-0.5">{activeSymbol}</p>
            <p className="text-sm font-bold text-white">${quote.price.toFixed(2)}</p>
            <p className={clsx('text-xs font-mono', quote.changePercent >= 0 ? 'text-green-400' : 'text-red-400')}>
              {quote.changePercent >= 0 ? '+' : ''}{quote.changePercent.toFixed(2)}%
            </p>
          </div>
          {consensus && (
            <div className="bg-bg-card border border-border-dim rounded-lg p-3">
              <p className="text-xs text-text-muted mb-0.5">Analyst Consensus</p>
              <p className="text-sm font-bold text-white">{consensus}</p>
              <p className="text-xs text-text-muted">{totalRatings} analysts</p>
            </div>
          )}
          {nextEarnings && (
            <div className="bg-bg-card border border-border-dim rounded-lg p-3">
              <p className="text-xs text-text-muted mb-0.5">Next Earnings</p>
              <p className="text-sm font-bold text-white">
                {new Date(nextEarnings.date + 'T12:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
              </p>
              {lastEarnings?.surprise != null && (
                <p className={clsx('text-xs font-mono', lastEarnings.surprise >= 0 ? 'text-green-400' : 'text-red-400')}>
                  Last: {lastEarnings.surprise >= 0 ? '+' : ''}{lastEarnings.surprise.toFixed(1)}% surprise
                </p>
              )}
            </div>
          )}
          {institutional && (
            <div className="bg-bg-card border border-border-dim rounded-lg p-3">
              <p className="text-xs text-text-muted mb-0.5">Inst. Ownership</p>
              <p className="text-sm font-bold text-white">{institutional.institutionPct.toFixed(1)}%</p>
              <p className="text-xs text-text-muted">Insider {institutional.insiderPct.toFixed(1)}%</p>
            </div>
          )}
        </div>
      )}

      {error && <div className="bg-bg-card border border-red-900/40 rounded-lg p-4 flex gap-2"><AlertCircle className="w-4 h-4 text-red-400 shrink-0 mt-0.5" /><p className="text-xs text-red-400">{error}</p></div>}
      {analysis && <AnalysisCard text={analysis} provider={provider} symbol={activeSymbol} />}
      {!analysis && !error && !loading && (
        <div className="bg-bg-card border border-border-dim rounded-lg p-8 text-center space-y-2">
          <TrendingUp className="w-8 h-8 text-text-muted/40 mx-auto" />
          <p className="text-sm text-text-muted">Enter a symbol and click Analyse</p>
          <p className="text-xs text-text-muted/60">Uses price, analyst ratings, earnings, and institutional data</p>
        </div>
      )}
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export function AICopilot() {
  const [tab, setTab] = useState<Tab>('market');
  const provider = getActiveProvider();

  return (
    <div className="p-4 space-y-4">
      <div className="flex items-center gap-2 flex-wrap">
        <Bot className="w-4 h-4 text-accent" />
        <h1 className="text-sm font-semibold text-white">AI Copilot</h1>
        <span className="text-xs px-1.5 py-0.5 rounded bg-accent/20 text-accent">Beta</span>
        <ProviderBadge />
      </div>

      {!provider && <NoKeyNote />}

      {/* Tabs */}
      <div className="flex border-b border-border-dim">
        <button
          onClick={() => setTab('market')}
          className={clsx('flex items-center gap-1.5 px-4 py-2 text-xs font-medium transition-colors', tab === 'market' ? 'text-accent border-b-2 border-accent' : 'text-text-muted hover:text-gray-300')}
        >
          <BarChart2 className="w-3.5 h-3.5" /> Market Overview
        </button>
        <button
          onClick={() => setTab('symbol')}
          className={clsx('flex items-center gap-1.5 px-4 py-2 text-xs font-medium transition-colors', tab === 'symbol' ? 'text-accent border-b-2 border-accent' : 'text-text-muted hover:text-gray-300')}
        >
          <TrendingUp className="w-3.5 h-3.5" /> Symbol Analysis
        </button>
      </div>

      {tab === 'market' ? <MarketTab /> : <SymbolTab />}
    </div>
  );
}
